sudo: false
language: node_js
node_js:
  - "6"

before_install:
  - npm install -g npm@^2.0.0

before_script:
  - npm prune

script:
  - npm run test:single
  - npm run check-coverage

after-success:
  - npm run report-coverage
